import Head from 'next/head';
import { Container, Row, Col } from 'react-bootstrap';
import SchoolCard from '../../components/school_cards/school_card';

const schools = ['ESCOM', 'ESCA', 'EST', 'ESIQIE', 'ESFM', 'UPIICSA'];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Unitramite</h1>
        <Container>
          <Row>
            {schools.map((school) => (
              <Col>
                <SchoolCard
                  key={school.toLowerCase()}
                  name={school}
                  src={`${school}.jpg`}
                />
              </Col>
            ))}
          </Row>
        </Container>
      </main>
    </>
  );
}
