import Head from 'next/head';
import { Container, Row, Col, Button } from 'react-bootstrap';
import SchoolCard, {
  SchoolCardProps,
} from '../../components/school_cards/school_card';
import schoolStore from '../../api/school.store';
import CustomNavBar from '../../components/navbar/navbar';
import { GetStaticProps } from 'next';

export default function Home({ schools }: { schools: SchoolCardProps[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CustomNavBar />
        <Container fluid>
          {schools.map((school) => (
            <SchoolCard key={school.id} {...school} />
          ))}
        </Container>
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = () => {
  schoolStore.initStore();
  const schools = schoolStore.getSchoolsCardProps();
  return {
    props: {
      schools,
    },
  };
};
